### ISSUE TITLE
Use Black Code Style

### ISSUE THREAD

**Issue by WilliamLwj** [WilliamLwj/PyXAB#14]
Please change all of our codes to follow the black style https://github.com/psf/black

**Comment by siamak4mo** [comment]
hi, I'd like to do this job.
i think running black over each ```.py``` file is what you need
am i right?

**Comment by WilliamLwj** [comment]
> hi, I'd like to do this job. i think running black over each `.py` file is what you need am i right?

Hi @siamak4mo. Thank you so much for offering to help! We really appreciate it. 

Unfortunately, we have already changed the code style to black and this issue should have been closed. It will serve as a reference for future pull requests to always follow the black style.

However, we are still actively developing our package, and there are many things that could need extra hands. Please consider starring and forking our repository, open issues for problems you have found / new features you would like to develop, and even contribute with your valuable codes! For example, right now, we really need some nice examples in our documentation (`docs/examples`), and documentations about the implemented algorithms/partitions, e.g., `PyXAB/partition/BinaryPartition.py`.

It's really exciting to see that people care about X-armed bandit!
